### ISSUE TITLE
Bug: Mp3 file starts jumping, then proceeds to next chapter

### ISSUE THREAD

**Issue by Bubblesss** [tomyri/Sabas#1]
An audiobook consisting of mp3 files that work with no problems on my PC, starts jumping on Sabas at around 4:00 mark. After a few seconds of jumping, it skips rest of the current chapter and proceeds to the next one. This happens with all chapters(=files).

**Comment by tomyri** [comment]
Can't reproduce that with my files. Could you provide example file?

**Comment by Bubblesss** [comment]
Sure,

https://docs.google.com/file/d/0B7qqzwfIhaGVdVdkcEx1MWFBQk0

https://docs.google.com/file/d/0B7qqzwfIhaGVTXZrLUpLclIxNlk

**Comment by tomyri** [comment]
Something weird with those files. Player doesn't update current position right. Same seems to happen with Jolla's Media app.

**Comment by Bubblesss** [comment]
I was gonna write another bug report about that :). Windows Media Player plays them ok, though. _shrug_

**Comment by tomyri** [comment]
Did a little test:
44.1kHz stereo -> ok
44.1kHz mono -> ok
22.05kHz stereo -> ok
22.05kHz mono -> fail (your files)

**Comment by Bubblesss** [comment]
Ok thanks for info, I know what files to avoid in the future. Since Jolla's media app has same issues, I guess fix will have to come from their side, IF it's coming?

**Comment by tomyri** [comment]
That's right. Already mentioned it on #sailfishos irc-channel but nobody seems to be interested.
