### ISSUE TITLE
Should save position periodically

### ISSUE THREAD

**Issue by tpikonen** [tomyri/Sabas#2]
Sabas seems to save the current position in the audiobook only when paused. Since Sabas also occasionally crashes, this leads to loss of position when restarting.

Sabas should save the current position also during playback, for example every 10 seconds.

**Comment by tomyri** [comment]
It saves position on exit and when going back to library page which should be enough, but mayby I put the timed save back there. Can you tell me more about those crashes? You have the latest version from Jolla's store?

**Comment by tpikonen** [comment]
Yes, I have the latest version. 

I've had a couple of crashes while listening with the device screen off. The crashes seem random, at least they do not repeat on the same position in the mp3 file. Hard to say more, since there is no debug output AFAIK.

**Comment by tomyri** [comment]
Added periodic save when playing.

I'm gonna do little more testing before pushing it to store. Added new RPMs to repo if someone want to test it. 

Please open new ticket if you figure out what causes those crashes.
