### ISSUE TITLE
Playback forgets current time

### ISSUE THREAD

**Issue by jonpacker** [tomyri/Sabas#5]
Seems to do this to me constantly. I would guess that it's caused by the app exiting abnormally. I've been affected by the frequent-restart bug that some people have been seeing lately and every time I restart, it seems to forgets the playback position.

I think I have also seen it do it when I have left the app inactive for a long period of time (a few hours) and then purged all of the apps (close-all).

**Comment by tomyri** [comment]
My best guess is that application is killed when saving settings. I try to figure something to prevent data loss.

**Comment by jonpacker** [comment]
It might work if you continually save the position while the book is playing, say every 5 seconds. I guess you can't rely on the destructor being called if the entire OS crashes abnormally, or when the app is in some kind of stasis (I don't know if that actually happens, but it would explain it losing position when closing after a long period of inactivity).

**Comment by tomyri** [comment]
Is playing continued from last position before crash or always from beginning?

Settings are saved periodically in next version.
