### ISSUE TITLE
Cover Art not always found

### ISSUE THREAD

**Issue by yjeanrenaud** [tomyri/Sabas#6]
I do have folder.jpg and AlbumArtSmall.jpg in the folders, as most media players use these and select the propper ones. Also, covers are embedded into the MP3 and m4a files. Sabas seems to recognize only AlbumArtSmall, which of course looks bad as it is only 74x74 px. So i deleted this file and now I got no cover anymore.

**Comment by tomyri** [comment]
I will add selection if there are multiple cover files. What comes covers embedded in audio files, don't hold your breath.

**Comment by tomyri** [comment]
Fixed version added to QA
