### ISSUE TITLE
Support directory change

### ISSUE THREAD

**Issue by Ray-Ven** [tomyri/Sabas#8]
As you can imagine, a lot of people keep their audiobooks on an sd-card. Please support directory change.

**Comment by tomyri** [comment]
I had simple option to change directory but stores QA did not like it, they demand a fully functional file chooser. I'll do that but it needs quite some work and is not first on my todo list.

There is easy work around that you can do.
Log in to your phone using ssh or terminal. Then create symlink.

```
ln -s /run/user/100000/media/sdcard/Audiobooks ~/Audiobooks
```

or

```
ln -s /run/user/100000/media/sdcard/Audiobooks ~/Documents/Audiobooks
```

In those examples books are on sd-card's Audiobook folder, but of course they don't need to be. Just adjust the first path to point folder holding them.

**Comment by tomyri** [comment]
If you want to speed this, consider voting this https://together.jolla.com/question/321/file-picker-needed/

**Comment by surfing** [comment]
Why don't you scan a folder 'audiobooks' on every sdcard partition?

**Comment by tomyri** [comment]
Folder can now be changed
